### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by agentphoenix** [anodyne/www#1]
- [x] Run user migrations
- [x] Run news migrations
- [x] Move domain name over
- [x] Sitemap
- [x] Add news items
- [x] Forum announcement
- [x] Twitter announcement
- [x] Facebook announcement
